npm_build:
  stage: build
  tags:
    - shared-fi
  image: node:8
  # Cache modules in between jobs
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - node_modules/
  script:
    - npm install --progress=false
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

deploy_to_aisa:
  stage: deploy
  image: alpine
  tags:
    - shared-fi
  script:
    - apk add --no-cache rsync openssh coreutils
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY_RSA" > ~/.ssh/id_analysis
    - chmod 600 ~/.ssh/id_analysis
    - ssh-keyscan aisa.fi.muni.cz >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - rsync -rav -e "ssh -v -i ~/.ssh/id_analysis" --delete dist/ xrehacek@aisa.fi.muni.cz:~/public_html/analysis-vis
